server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }

  # repassa /api/... para a api pela network do compose (DNS interno: api)
  location /api/ {
    proxy_pass http://api:3005/;
  }
}
